spring:
  datasource:
    url: "jdbc:h2:mem:db"
    username: "foodtruck"
    password: "foodtruck"
    driver-class-name: "org.h2.Driver"
  jpa:
    hibernate:
      ddl-auto: "create-drop"
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.H2Dialect"
        format_sql: true
    defer-datasource-initialization: true
